apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: paskibra
  labels:
    app: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel
          image: docker.io/library/laravel-paskibra:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: APP_NAME
              value: "PaskibraRecruitment"
            - name: APP_ENV
              value: "production"
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: "http://localhost:30080"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: APP_KEY
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_HOST
              value: "192.168.100.49"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "paskibra_db"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secret
                  key: DB_PASSWORD
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: CACHE_STORE
              value: "redis"
            - name: SESSION_DRIVER
              value: "redis"
            - name: QUEUE_CONNECTION
              value: "redis"
            - name: LOG_CHANNEL
              value: "stderr"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: paskibra
spec:
  type: NodePort
  selector:
    app: laravel-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080